anchor_version = "0.24.2"

[registry]
url = "https://anchor.projectserum.com"

# [features]
# seeds = true

[programs.localnet]
dexloan_listings = "8hSdpqHU7jz4C6C1kHUPQNMqBcC76n1BFXbHaTwd9X4c"

[programs.devnet]
dexloan_listings = "8hSdpqHU7jz4C6C1kHUPQNMqBcC76n1BFXbHaTwd9X4c"

[programs.mainnet]
dexloan_listings = "8hSdpqHU7jz4C6C1kHUPQNMqBcC76n1BFXbHaTwd9X4c"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.mainnet-beta.solana.com" 

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"