[programs.localnet]
dexloan = "AqLBJQk2vRmJvX3hT43RQrWBfy66oXLsHYd136JHh45R"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/grantfindlay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
